services:
  can-bridge:
    container_name: can-bridge
    build:
      context: ./can-bridge
      dockerfile: Dockerfile
    image: ghcr.io/schommie/ev-can-bridge:latest
    network_mode: host
    restart: unless-stopped

  gui:
    container_name: gui
    build:
      context: ./gui
      dockerfile: Dockerfile
    image: ghcr.io/schommie/ev-gui:latest
    network_mode: host
    restart: unless-stopped
