services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: daq-backend:latest
    ports:
      - "8080:8080"
    network_mode: "host"

  gui:
    build:
      context: ./gui
      dockerfile: Dockerfile
    image: daq-gui:latest
    ports:
      - "8080:80"