// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BmsTelemetry } from "./BmsTelemetry";
import type { DaqTelemetry } from "./DaqTelemetry";
import type { DeviceStatus } from "./DeviceStatus";

export type BackendEventData = { "type": "deviceRegistrySnapshot", devices: Array<DeviceStatus>, } | { "type": "deviceStatusChanged", device: DeviceStatus, } | { "type": "daqTelemetry", telemetry: DaqTelemetry, } | { "type": "bmsTelemetry", telemetry: BmsTelemetry, } | { "type": "backendError", message: string, };
