// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BmsTemperatureReadings } from "./BmsTemperatureReadings";
import type { BmsVoltageReadings } from "./BmsVoltageReadings";
import type { Device } from "./Device";
import type { FaultSeverity } from "./FaultSeverity";
import type { Percent } from "./Percent";

export type BmsTelemetry = { "type": "voltages", source: Device, readings: BmsVoltageReadings, } | { "type": "temperatures", source: Device, readings: BmsTemperatureReadings, } | { "type": "balancing", source: Device, active_cell: number, duty_cycle: Percent, } | { "type": "faults", source: Device, code: number, severity: FaultSeverity, };
