// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DeviceStatus = { nodeId: number, name: string, system: string, online: boolean, lastSeenMsAgo: bigint | null, lastError: string | null, };
