// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Device } from "./Device";
import type { ImuSample } from "./ImuSample";
import type { MeasurementValue } from "./MeasurementValue";
import type { TemperatureSample } from "./TemperatureSample";

export type DaqTelemetry = { "type": "temperature", source: Device, samples: [TemperatureSample, TemperatureSample, TemperatureSample, TemperatureSample, TemperatureSample, TemperatureSample, TemperatureSample, TemperatureSample, TemperatureSample, TemperatureSample, TemperatureSample, TemperatureSample, TemperatureSample, TemperatureSample, TemperatureSample, TemperatureSample], } | { "type": "imu", source: Device, samples: [ImuSample, ImuSample, ImuSample, ImuSample, ImuSample], } | { "type": "tbd", source: Device, value: MeasurementValue, };
