// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Device = "bms" | "vcu" | "raspi" | "nodeFL" | "nodeFR" | "nodeRL" | "nodeRR" | "nodeDash" | "nodeRideHeight" | "nodePDMTB" | "nodePDMDASH" | "nodePDMPCBPanel";
