// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Device } from "./Device";

export type VcuRequest = { "command": "ping", target: Device, } | { "command": "reset", target: Device, };
