// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BmsRequest } from "./BmsRequest";
import type { DaqRequest } from "./DaqRequest";
import type { VcuRequest } from "./VcuRequest";

export type WsIncoming = { "system": "daq", "request": DaqRequest } | { "system": "bms", "request": BmsRequest } | { "system": "vcu", "request": VcuRequest };
