// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BmsMessage } from "./BmsMessage";
import type { DaqMessage } from "./DaqMessage";
import type { DeviceStatus } from "./DeviceStatus";
import type { VcuMessage } from "./VcuMessage";

export type WsOutgoing = { "type": "daq", "event": DaqMessage } | { "type": "bms", "event": BmsMessage } | { "type": "vcu", "event": VcuMessage } | { "type": "deviceStatusSnapshot", "event": { devices: Array<DeviceStatus>, } } | { "type": "deviceStatusChanged", "event": { device: DeviceStatus, } } | { "type": "error", "event": { message: string, } };
